FROM node:lts AS builder

WORKDIR /repo
COPY ../../ ./

RUN corepack enable && corepack prepare pnpm@latest --activate
RUN pnpm install --filter ./apps/project-a...
WORKDIR /repo/apps/project-a
RUN pnpm build

FROM nginx:latest
COPY --from=builder /repo/apps/project-a/dist /usr/share/nginx/html
