FROM node:lts AS builder

WORKDIR /repo
COPY ../../ ./

RUN corepack enable && corepack prepare pnpm@latest --activate
RUN pnpm install --filter ./apps/project-b...
WORKDIR /repo/apps/project-b
RUN pnpm build

FROM nginx:latest
COPY --from=builder /repo/apps/project-b/dist /usr/share/nginx/html
