FROM nginx:latest

# Copy the correct config file
COPY nginx/default.prod.conf /etc/nginx/conf.d/default.conf

# Copy build outputs from the context (now relative to monorepo root)
COPY apps/project-a/dist /usr/share/nginx/html/project-a
COPY apps/project-b/dist /usr/share/nginx/html/project-b
